-- ITEMS
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Shoes', 'These go on your feet');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Shirt', 'Covers your midsection');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Pants', 'Covers your bottom half');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Glasses', 'Corrects your eyesight');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Sun Glasses', 'Makes it easier to see when it''s bright out');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Hat', 'Protect the top of your head from direct sunlight');
INSERT INTO ITEM (NAME, DESCRIPTION) VALUES ('Gloves', 'Cover your digits when it gets cold outside');

-- CUSTOMERS
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Homer', 'Simpson', '123 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Marge', 'Simpson', '123 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Bart', 'Simpson', '123 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Lisa', 'Simpson', '123 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Maggie', 'Simpson', '123 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Ned', 'Flanders', '122 Main Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Milton', 'Van Houten', '435 Spring Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Edna', 'Krabapple', '789 Fairview Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Nelson', 'Muntz', '1079 That Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Moe', 'Szyslak', '10793 High Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Waylon', 'Smithers', '7 Rich Street', 'Springfield', 'IL', '12345', 'US');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY) VALUES ('Mr.', 'Burns', '7 Rich Street', 'Springfield', 'IL', '12346', 'US');

-- CUSTOMER_ORDERS
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 1);
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 2);
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 3);
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 6);
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 5);
INSERT INTO CUSTOMER_ORDER (CUSTOMER_ID, ITEM_ID) VALUES (1, 1);
